from __future__ import annotations

from enum import Enum


class ReasonId(str, Enum):
    INVALID_CONTRACT_VERSION = "INVALID_CONTRACT_VERSION"
    INVALID_REQUEST = "INVALID_REQUEST"
    HASHING_FAILED = "HASHING_FAILED"
    COMPONENT_ERROR = "COMPONENT_ERROR"
    COMPONENT_INVALID_RESPONSE = "COMPONENT_INVALID_RESPONSE"
    COMPONENT_MISSING = "COMPONENT_MISSING"
    DENY_BY_POLICY = "DENY_BY_POLICY"
    INTERNAL_ERROR = "INTERNAL_ERROR"
